"""Deterministic close-out transaction for metadata-managed Sopify plans."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
import re
import shutil
from pathlib import Path
from typing import Mapping

from .models import KbArtifact, PlanArtifact, RuntimeConfig
from .state import StateStore, iso_now

_REQUIRED_METADATA_KEYS = (
    "plan_id",
    "feature_key",
    "level",
    "lifecycle_state",
    "blueprint_obligation",
    "archive_ready",
)
_SUPPORTED_LEVELS = {"light", "standard", "full"}
_SUPPORTED_LIFECYCLE_STATES = {"active", "ready_for_verify"}
_SUPPORTED_BLUEPRINT_OBLIGATIONS = {"index_only", "review_required", "design_required"}
_FRONT_MATTER_RE = re.compile(r"\A---\n(?P<front>.*?)\n---\n(?P<body>.*)\Z", re.DOTALL)
@dataclass(frozen=True)
class ManagedPlanDocument:
    """Normalized metadata view for a runtime-managed plan document."""

    plan_dir: Path
    relative_plan_dir: str
    metadata_path: Path
    relative_metadata_path: str
    plan_id: str
    feature_key: str
    level: str
    lifecycle_state: str
    blueprint_obligation: str
    archive_ready: bool
    front_matter: str
    body: str
    raw_text: str


@dataclass(frozen=True)
class FinalizeResult:
    """Structured result of the finalize transaction."""

    archived_plan: PlanArtifact | None
    kb_artifact: KbArtifact | None
    notes: tuple[str, ...]


@dataclass(frozen=True)
class _BlueprintObligationStatus:
    blocked_reason: str | None
    notes: tuple[str, ...]


def finalize_plan(
    *,
    config: RuntimeConfig,
    state_store: StateStore,
    current_plan: PlanArtifact | None,
) -> FinalizeResult:
    """Finalize the active metadata-managed plan into history.

    First version boundary:
    - only metadata-managed plans generated by the new runtime are supported
    - explicit `~go finalize` is the close-out checkpoint
    - legacy plans are rejected instead of being auto-migrated
    """
    if current_plan is None:
        return FinalizeResult(
            archived_plan=None,
            kb_artifact=None,
            notes=(_text(config.language, "no_active_plan"),),
        )

    plan_dir = config.workspace_root / current_plan.path
    if not plan_dir.exists() or not plan_dir.is_dir():
        return FinalizeResult(
            archived_plan=None,
            kb_artifact=None,
            notes=(_text(config.language, "missing_plan_dir", path=current_plan.path),),
        )

    managed_plan = _load_managed_plan(plan_dir, config=config)
    if managed_plan is None:
        return FinalizeResult(
            archived_plan=None,
            kb_artifact=None,
            notes=(_text(config.language, "legacy_unsupported"),),
        )

    if managed_plan.plan_id != current_plan.plan_id:
        return FinalizeResult(
            archived_plan=None,
            kb_artifact=None,
            notes=(
                _text(
                    config.language,
                    "metadata_mismatch",
                    state_plan_id=current_plan.plan_id,
                    document_plan_id=managed_plan.plan_id,
                ),
            ),
        )

    obligation = _evaluate_blueprint_obligation(
        config=config,
        managed_plan=managed_plan,
        created_at=current_plan.created_at,
    )
    if obligation.blocked_reason is not None:
        return FinalizeResult(
            archived_plan=None,
            kb_artifact=None,
            notes=(*obligation.notes, obligation.blocked_reason),
        )

    archive_dir = _archive_target_dir(config=config, plan_id=managed_plan.plan_id)
    if archive_dir.exists():
        return FinalizeResult(
            archived_plan=None,
            kb_artifact=None,
            notes=(
                _text(
                    config.language,
                    "archive_exists",
                    path=str(archive_dir.relative_to(config.workspace_root)),
                ),
            ),
        )

    archive_dir.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(plan_dir), str(archive_dir))

    archived_metadata_path = archive_dir / managed_plan.metadata_path.name
    archived_text = _render_document(
        _replace_front_matter_fields(
            managed_plan.front_matter,
            {
                "lifecycle_state": "archived",
                "archive_ready": "true",
            },
        ),
        managed_plan.body,
    )
    archived_metadata_path.write_text(archived_text, encoding="utf-8")

    archived_plan = PlanArtifact(
        plan_id=current_plan.plan_id,
        title=current_plan.title,
        summary=current_plan.summary,
        level=current_plan.level,
        path=str(archive_dir.relative_to(config.workspace_root)),
        files=_archived_files(current_plan=current_plan, archive_dir=archive_dir, workspace_root=config.workspace_root),
        created_at=current_plan.created_at,
    )

    history_index_path = _update_history_index(config=config, archived_plan=archived_plan)
    readme_path = _refresh_blueprint_readme(config=config, archived_plan=archived_plan)

    state_store.reset_active_flow()

    kb_files = tuple(
        path
        for path in (
            str(readme_path.relative_to(config.workspace_root)),
            str(history_index_path.relative_to(config.workspace_root)),
        )
    )
    notes = (
        *obligation.notes,
        _text(config.language, "archived", path=archived_plan.path),
        _text(config.language, "state_cleared"),
    )
    return FinalizeResult(
        archived_plan=archived_plan,
        kb_artifact=KbArtifact(mode=config.kb_init, files=kb_files, created_at=iso_now()),
        notes=notes,
    )


def _load_managed_plan(plan_dir: Path, *, config: RuntimeConfig) -> ManagedPlanDocument | None:
    metadata_path = _pick_metadata_file(plan_dir)
    if metadata_path is None:
        return None

    raw_text = metadata_path.read_text(encoding="utf-8")
    match = _FRONT_MATTER_RE.match(raw_text)
    if match is None:
        return None

    front_matter = match.group("front")
    body = match.group("body")
    metadata = _parse_top_level_metadata(front_matter)
    if any(key not in metadata for key in _REQUIRED_METADATA_KEYS):
        return None

    level = metadata["level"]
    lifecycle_state = metadata["lifecycle_state"]
    blueprint_obligation = metadata["blueprint_obligation"]
    if level not in _SUPPORTED_LEVELS or lifecycle_state not in _SUPPORTED_LIFECYCLE_STATES:
        return None
    if blueprint_obligation not in _SUPPORTED_BLUEPRINT_OBLIGATIONS:
        return None

    return ManagedPlanDocument(
        plan_dir=plan_dir,
        relative_plan_dir=str(plan_dir.relative_to(config.workspace_root)),
        metadata_path=metadata_path,
        relative_metadata_path=str(metadata_path.relative_to(config.workspace_root)),
        plan_id=metadata["plan_id"],
        feature_key=metadata["feature_key"],
        level=level,
        lifecycle_state=lifecycle_state,
        blueprint_obligation=blueprint_obligation,
        archive_ready=_parse_bool(metadata["archive_ready"]),
        front_matter=front_matter,
        body=body,
        raw_text=raw_text,
    )


def _pick_metadata_file(plan_dir: Path) -> Path | None:
    for filename in ("plan.md", "tasks.md"):
        candidate = plan_dir / filename
        if candidate.exists() and candidate.is_file():
            return candidate
    return None


def _parse_top_level_metadata(front_matter: str) -> dict[str, str]:
    metadata: dict[str, str] = {}
    for line in front_matter.splitlines():
        if not line or line.startswith(" ") or ":" not in line:
            continue
        key, _, value = line.partition(":")
        metadata[key.strip()] = value.strip()
    return metadata


def _parse_bool(value: str) -> bool:
    return value.strip().lower() == "true"


def _replace_front_matter_fields(front_matter: str, updates: Mapping[str, str]) -> str:
    lines = front_matter.splitlines()
    remaining = dict(updates)
    for index, line in enumerate(lines):
        if not line or line.startswith(" ") or ":" not in line:
            continue
        key, _, _ = line.partition(":")
        key = key.strip()
        if key in remaining:
            lines[index] = f"{key}: {remaining.pop(key)}"
    if remaining:
        missing = ", ".join(sorted(remaining))
        raise ValueError(f"Missing expected metadata keys while updating front matter: {missing}")
    return "\n".join(lines)


def _render_document(front_matter: str, body: str) -> str:
    return f"---\n{front_matter}\n---\n{body}"


def _evaluate_blueprint_obligation(
    *,
    config: RuntimeConfig,
    managed_plan: ManagedPlanDocument,
    created_at: str,
) -> _BlueprintObligationStatus:
    if managed_plan.blueprint_obligation == "index_only":
        return _BlueprintObligationStatus(
            blocked_reason=None,
            notes=(_text(config.language, "index_only_satisfied"),),
        )

    plan_created_at = _parse_created_at(created_at)
    plan_document_time = datetime.fromtimestamp(managed_plan.metadata_path.stat().st_mtime, tz=plan_created_at.tzinfo)
    reference_time = max(plan_created_at, plan_document_time)
    deep_files = (
        config.runtime_root / "blueprint" / "background.md",
        config.runtime_root / "blueprint" / "design.md",
        config.runtime_root / "blueprint" / "tasks.md",
    )
    changed_files = tuple(
        str(path.relative_to(config.workspace_root))
        for path in deep_files
        if path.exists() and datetime.fromtimestamp(path.stat().st_mtime, tz=reference_time.tzinfo) > reference_time
    )
    if changed_files:
        return _BlueprintObligationStatus(
            blocked_reason=None,
            notes=(_text(config.language, "deep_blueprint_updated", paths=", ".join(changed_files)),),
        )

    if managed_plan.blueprint_obligation == "review_required":
        return _BlueprintObligationStatus(
            blocked_reason=None,
            notes=(_text(config.language, "review_required_warning"),),
        )

    return _BlueprintObligationStatus(
        blocked_reason=_text(config.language, "design_required_blocked"),
        notes=(),
    )


def _parse_created_at(value: str) -> datetime:
    if value:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    return datetime.now().astimezone()


def _archive_target_dir(*, config: RuntimeConfig, plan_id: str) -> Path:
    archive_month = datetime.now().strftime("%Y-%m")
    return config.runtime_root / "history" / archive_month / plan_id


def _archived_files(*, current_plan: PlanArtifact, archive_dir: Path, workspace_root: Path) -> tuple[str, ...]:
    source_root = current_plan.path.rstrip("/")
    target_root = str(archive_dir.relative_to(workspace_root))
    archived_files: list[str] = []
    for path in current_plan.files:
        if path.startswith(source_root):
            archived_files.append(path.replace(source_root, target_root, 1))
        else:
            archived_files.append(path)
    return tuple(archived_files)


def _refresh_blueprint_readme(*, config: RuntimeConfig, archived_plan: PlanArtifact) -> Path:
    readme_path = config.runtime_root / "blueprint" / "README.md"
    readme_path.parent.mkdir(parents=True, exist_ok=True)
    if not readme_path.exists():
        # Keep the refresh path resilient even if the workspace skipped the initial bootstrap.
        from .kb import _blueprint_readme_stub  # local import avoids widening kb.py dependencies

        readme_path.write_text(_blueprint_readme_stub(config), encoding="utf-8")

    content = readme_path.read_text(encoding="utf-8")
    updated = content
    for section, block in _readme_blocks(config=config, archived_plan=archived_plan).items():
        updated = _replace_managed_block(updated, section=section, block=block)
    if updated != content:
        readme_path.write_text(updated, encoding="utf-8")
    return readme_path


def _replace_managed_block(content: str, *, section: str, block: str) -> str:
    start = f"<!-- sopify:auto:{section}:start -->"
    end = f"<!-- sopify:auto:{section}:end -->"
    pattern = re.compile(rf"{re.escape(start)}.*?{re.escape(end)}", re.DOTALL)
    replacement = f"{start}\n{block}\n{end}"
    if pattern.search(content) is None:
        return content
    return pattern.sub(replacement, content, count=1)


def _readme_blocks(*, config: RuntimeConfig, archived_plan: PlanArtifact) -> dict[str, str]:
    archive_link = _archive_link_for_blueprint(archived_plan.path)
    if config.language == "en-US":
        return {
            "goal": (
                f"- Keep `{config.workspace_root.name or 'project'}` discoverable through a long-lived blueprint index.\n"
                "- Use the finalize transaction to close the active metadata-managed plan before the next planning round."
            ),
            "overview": (
                "- blueprint: tracked long-lived project facts\n"
                "- plan: active working plan created per task\n"
                "- history: finalized archives produced by `~go finalize`\n"
                "- replay: optional replay capability"
            ),
            "architecture": (
                "```text\n"
                ".sopify-skills/\n"
                "├── blueprint/\n"
                "├── plan/\n"
                "├── history/\n"
                "├── state/\n"
                "└── replay/\n"
                "```"
            ),
            "contracts": (
                "- Create `blueprint/README.md` on the first real-project trigger.\n"
                "- Populate deeper blueprint files on the first plan lifecycle.\n"
                "- Finalize only metadata-managed plans generated by the new runtime.\n"
                "- `review_required` warns when deep blueprint updates are missing; `design_required` blocks finalize."
            ),
            "focus": (
                f"- Latest finalized plan: `{archived_plan.title}` -> `{archived_plan.path}`\n"
                "- There is no active plan after finalize; the next planning round will create a fresh one."
            ),
            "read-next": (
                "- [Technical Conventions](../project.md)\n"
                "- [Project Overview](../wiki/overview.md)\n"
                "- [Blueprint Design](./design.md)\n"
                f"- Latest archive: `{archive_link}`"
            ),
        }

    return {
        "goal": (
            f"- 持续把 `{config.workspace_root.name or 'project'}` 的长期事实收口到蓝图索引。\n"
            "- 通过 finalize 事务完成活动 metadata-managed plan 的正式收口，再进入下一轮规划。"
        ),
        "overview": (
            "- blueprint: 长期项目真相，默认入库\n"
            "- plan: 每轮任务生成的活动方案\n"
            "- history: 由 `~go finalize` 产出的历史归档\n"
            "- replay: 可选回放能力"
        ),
        "architecture": (
            "```text\n"
            ".sopify-skills/\n"
            "├── blueprint/\n"
            "├── plan/\n"
            "├── history/\n"
            "├── state/\n"
            "└── replay/\n"
            "```"
        ),
        "contracts": (
            "- 首次真实项目触发时创建 `blueprint/README.md`\n"
            "- 首次进入 plan 生命周期时补齐深层 blueprint 文件\n"
            "- 只有新 runtime 生成的 metadata-managed plan 支持 finalize\n"
            "- `review_required` 缺少深层 blueprint 更新时仅警告；`design_required` 会阻断收口"
        ),
        "focus": (
            f"- 最近收口方案：`{archived_plan.title}` -> `{archived_plan.path}`\n"
            "- 当前已无活动 plan；下一轮规划会重新创建新的活动方案。"
        ),
        "read-next": (
            "- [项目技术约定](../project.md)\n"
            "- [项目概览](../wiki/overview.md)\n"
            "- [蓝图设计](./design.md)\n"
            f"- 最近归档: `{archive_link}`"
        ),
    }


def _update_history_index(*, config: RuntimeConfig, archived_plan: PlanArtifact) -> Path:
    history_index = config.runtime_root / "history" / "index.md"
    history_index.parent.mkdir(parents=True, exist_ok=True)
    existing = history_index.read_text(encoding="utf-8") if history_index.exists() else _history_index_stub(config.language)
    updated = _render_history_index(existing, archived_plan=archived_plan, language=config.language)
    if updated != existing:
        history_index.write_text(updated, encoding="utf-8")
    return history_index


def _render_history_index(existing: str, *, archived_plan: PlanArtifact, language: str) -> str:
    entry = _history_entry(archived_plan=archived_plan, language=language)
    if language == "en-US":
        header = "# Change History Index\n\nRecords completed plan archives for future lookup.\n\n## Index\n\n"
        placeholder = "No archived plans yet."
    else:
        header = "# 变更历史索引\n\n记录已归档的方案，便于后续查询。\n\n## 索引\n\n"
        placeholder = "当前暂无已归档方案。"

    body = existing
    if "## Index" in existing or "## 索引" in existing:
        _, _, remainder = existing.partition("## Index\n\n" if language == "en-US" else "## 索引\n\n")
        body = remainder
    lines = [line for line in body.splitlines() if line.strip() and line.strip() != placeholder]
    lines = [line for line in lines if archived_plan.plan_id not in line]
    lines.insert(0, entry)
    return header + "\n".join(lines) + "\n"


def _history_entry(*, archived_plan: PlanArtifact, language: str) -> str:
    date_text = datetime.now().strftime("%Y-%m-%d")
    link = archived_plan.path.removeprefix(".sopify-skills/history/")
    if language == "en-US":
        return f"- `{date_text}` [`{archived_plan.plan_id}`]({link}/) - {archived_plan.level} - {archived_plan.title}"
    return f"- `{date_text}` [`{archived_plan.plan_id}`]({link}/) - {archived_plan.level} - {archived_plan.title}"


def _history_index_stub(language: str) -> str:
    if language == "en-US":
        return "# Change History Index\n\nRecords completed plan archives for future lookup.\n\n## Index\n\nNo archived plans yet.\n"
    return "# 变更历史索引\n\n记录已归档的方案，便于后续查询。\n\n## 索引\n\n当前暂无已归档方案。\n"


def _archive_link_for_blueprint(archived_plan_path: str) -> str:
    return "../" + archived_plan_path.removeprefix(".sopify-skills/")


def _text(language: str, key: str, **kwargs: str) -> str:
    messages = {
        "en-US": {
            "no_active_plan": "No active metadata-managed plan is available to finalize",
            "missing_plan_dir": "Active plan directory is missing: {path}",
            "legacy_unsupported": "Finalize only supports metadata-managed plans generated by the new runtime; legacy plans are not auto-migrated",
            "metadata_mismatch": "Plan metadata mismatch: state plan_id={state_plan_id} but document plan_id={document_plan_id}",
            "archive_exists": "Archive target already exists: {path}",
            "archived": "Plan archived to {path}",
            "state_cleared": "Active runtime state cleared",
            "index_only_satisfied": "Blueprint obligation satisfied: index_only",
            "deep_blueprint_updated": "Deep blueprint updated after plan creation: {paths}",
            "review_required_warning": "Blueprint review warning: no deep blueprint update detected; finalize proceeds because obligation is review_required",
            "design_required_blocked": "Finalize blocked: full/design_required plans must update blueprint/background.md, blueprint/design.md, or blueprint/tasks.md after plan creation",
        },
        "zh-CN": {
            "no_active_plan": "当前没有可收口的 metadata-managed 活动方案",
            "missing_plan_dir": "当前活动方案目录不存在：{path}",
            "legacy_unsupported": "finalize 仅支持新 runtime 生成的 metadata-managed plan，旧遗留 plan 不会被自动迁移",
            "metadata_mismatch": "方案元数据不一致：state plan_id={state_plan_id}，文档 plan_id={document_plan_id}",
            "archive_exists": "归档目标已存在：{path}",
            "archived": "方案已归档到 {path}",
            "state_cleared": "已清理活动运行时状态",
            "index_only_satisfied": "blueprint obligation 已满足：index_only",
            "deep_blueprint_updated": "已检测到 plan 创建后的深层 blueprint 更新：{paths}",
            "review_required_warning": "blueprint 审核提醒：未检测到深层 blueprint 更新，但当前 obligation=review_required，允许继续收口",
            "design_required_blocked": "收口被阻断：full/design_required 方案要求在 plan 创建后更新 blueprint/background.md、blueprint/design.md 或 blueprint/tasks.md",
        },
    }
    locale = "en-US" if language == "en-US" else "zh-CN"
    template = messages[locale][key]
    return template.format(**kwargs)
